### ISSUE TITLE
Tinypng: отображение некорректных размеров изображения из-за несоответствия формулы расчета отображаемого и загружаемого размера

### ISSUE THREAD

**Issue by ElenaVeselovskaya** [ElenaVeselovskaya/Bugs#1]
## Описание 
Формула расчета отображаемого размера изображения (1MB = 1 000 000 байт) не соответствует формуле расчета при загрузке изображения (1MB = 1 048 576 байт).
Отображаемый размер загруженного изображения не соответствует информации предоставленной на сайте: «max 5MB».

## Входные данные
Веб-сайт по адресу www.tinypng.org
Количество: любое
Типы файлов: любые
Размер: любой 
Вариант загрузки: любой
Имена файлов: любые валидные
Веб-браузеры: Chrome (70.0.3538.77, 64бит), Яндекс (18.9.1.954)

## Предусловия
Перед началом выполнения страница полностью перезагружается.

## Важность
Низкая

## Воспроизводимость
Всегда
## Шаги воспроизведения

Шаги                       | Ожидаемый результат | Фактический результат  
----------------------|----------------------------|---------------------------
Открыть веб-сервис | Веб-сервис функционирует | Pass
Загрузить указанным во входных данных вариантом файлы |1. Изображения загружены<br>2. Отображён размер загруженного изображения<br>3. Индикатор сжатия – зелёный <br>4. % сжатия – больше или равно 0<br>5. Подсчитан общий процент сжатия|  **Размеры отображены некорректно** (скриншот с ошибкой). При расчете по единой формуле (1MB = 1 048 576 байт) и округление в большую сторону до 1 цифры после запятой отображаемые размеры должны выглядеть следующим образом: изображение invalid = 5,1mb ( > max 5mb, файл не сжат), изображение valid  = 5,0mb (< max 5mb, файл сжат)   
Скачать все файлы |1. Скачивается архив со всеми файлами<br>2. Архив разархивируется<br>3. Размеры (в mb) изображений соответствуют указанным на сайте<br>3. Изображения открываются стандартной программой для просмотра изображений<br>4. Высота и ширина изображений соответствует исходным.
Результат выполнения теста | | **Fail**

## Приложения
Изображение Invalid
![invalid](https://user-images.githubusercontent.com/44900034/48270354-ee358d80-e44a-11e8-9302-bb2aa20f94f1.jpg)

Изображение valid 
![valid](https://user-images.githubusercontent.com/44900034/48270431-1c1ad200-e44b-11e8-8c74-90de929ae4f5.jpg)

Скриншот с ошибкой: 
1. изображение несжатого файла;
1. изображение сжатого файла.
![screenshot 2018-11-08 18 27 12](https://user-images.githubusercontent.com/44900034/48269865-a5c9a000-e449-11e8-8bd5-3337b0782a87.png)

**Comment by coursar** [comment]
@ElenaVeselovskaya, попробуйте из описания бага сделать для него название, чтобы по названию было всё понятно.

По замечаниям:
1. Во входных данных указано файл до 5Mb, хотя вы использовали больше
1. Проверяли ли в других браузерах? Если проверяли, то почему не отразили?
1. Тест-кейс вставлять не нужно (у вас для этого есть **Шаги воспроизведения**)

**Comment by ElenaVeselovskaya** [comment]
исправлено

**Comment by coursar** [comment]
@ElenaVeselovskaya, если вы не проверяли 3 шаг (в шагах по воспроизведению), лучше его исключить. В остальном всё ок.
